image: curlimages/curl:latest

stages:
  - upload

upload:
  variables:
    TERRAFORM_MODULE_DIR: ${CI_PROJECT_DIR}
    TERRAFORM_MODULE_NAME: terraform-aws-vpc
    TERRAFORM_MODULE_SYSTEM: aws
  stage: upload
  script:
    - |
      TERRAFORM_MODULE_VERSION=$( echo $CI_COMMIT_TAG | sed -r "s/.*([0-9]+.[0-9]+.[0-9]+)/\1/g" )
      tar -cvzf ${TERRAFORM_MODULE_NAME}-${TERRAFORM_MODULE_SYSTEM}-${TERRAFORM_MODULE_VERSION}.tgz -C ${TERRAFORM_MODULE_DIR} --exclude=./.git --exclude=./.gitignore --exclude=./.gitlab-ci.yml --exclude=./aws-frontend-module.code-workspace .
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${TERRAFORM_MODULE_NAME}-${TERRAFORM_MODULE_SYSTEM}-${TERRAFORM_MODULE_VERSION}.tgz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/terraform/modules/${TERRAFORM_MODULE_SYSTEM}/${TERRAFORM_MODULE_NAME}/${TERRAFORM_MODULE_VERSION}/file"
  rules:
      - if: $CI_COMMIT_TAG
